### ISSUE TITLE
Movement Presets | Dropdown

### ISSUE THREAD

**Issue by MonkeyShark** [Xenthio/XMovement#1]
A dropdown that allows you to select different games, a la Left 4 Dead 2, Half-Life 2, etc. as a base for the values. Modifiable once selected, but just generally start with these.

If you're avoiding copyright infringement, the values are likely not going to be exact enough for it to be a problem in general. Main problem would be the names, in which you could just give them parody / more subtle names like "Crowbar", "Green Flu".

Not a massive priority right now, but let me know if you'd want help working on this. I can try to figure out good presets.

Alternatively, maybe have a Google Doc attached to the Github if you don't want it directly inside the engine, I could help with this as well.

**Comment by Xenthio** [comment]
Added some
