### ISSUE TITLE
Auto Zoom in Third Person

### ISSUE THREAD

**Issue by MonkeyShark** [Xenthio/XMovement#2]
The default player controller with S&box has automatic zooming for when the camera is near an object. This prevents clipping. Implement something similar, or just take the code from the default controller.

This should be a toggle / boolean in the complex character.

**Comment by MonkeyShark** [comment]
Some images to demonstrate
![image](https://github.com/user-attachments/assets/eef729b9-4ce5-49b8-a8a3-7c11a68e7c79)
![image](https://github.com/user-attachments/assets/69283c63-4355-48b7-85ad-d218cc7ab010)

**Comment by Xenthio** [comment]
Done, reopen the issue if it's not quite to your satisfaction.
